from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
)
from typing import List, Optional
from datetime import datetime
import io

from core.extraction import BloodParameter


def generate_pdf_report(
    parameters: List[BloodParameter],
    pattern_findings: List[dict],
    context_notes: List[dict],
    summary: str,
    recommendations: List[str],
    age: Optional[int] = None,
    gender: Optional[str] = None
) -> bytes:
    """
    Generates a complete PDF report combining all analysis results.
    Returns the PDF as bytes (suitable for Streamlit download button).
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter,
                             topMargin=0.6 * inch, bottomMargin=0.6 * inch)
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "CustomTitle", parent=styles["Title"], fontSize=20, spaceAfter=6
    )
    heading_style = ParagraphStyle(
        "CustomHeading", parent=styles["Heading2"], spaceBefore=16, spaceAfter=8,
        textColor=colors.HexColor("#1a1a2e")
    )
    body_style = styles["Normal"]

    story = []

    # Title
    story.append(Paragraph("Health Diagnostics AI — Blood Report Analysis", title_style))
    story.append(Paragraph(
        f"Generated on {datetime.now().strftime('%B %d, %Y')}", body_style
    ))
    if age or gender:
        context_line = f"Age: {age or 'N/A'} | Gender: {gender or 'N/A'}"
        story.append(Paragraph(context_line, body_style))
    story.append(Spacer(1, 12))

    # Extracted Parameters Table
    story.append(Paragraph("Extracted Parameters", heading_style))
    table_data = [["Parameter", "Result", "Flag", "Reference Range", "Unit"]]
    for p in parameters:
        table_data.append([p.parameter, p.result, p.flag, p.reference_range, p.unit])

    table = Table(table_data, repeatRows=1, colWidths=[1.7*inch, 0.8*inch, 0.8*inch, 1.3*inch, 0.7*inch])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2d2d44")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f5f5f5")]),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    story.append(table)
    story.append(Spacer(1, 12))

    # Abnormal Results
    abnormal = [p for p in parameters if p.flag.lower() != "normal"]
    if abnormal:
        story.append(Paragraph("Results Needing Attention", heading_style))
        for p in abnormal:
            story.append(Paragraph(
                f"<b>{p.parameter}</b>: {p.result} {p.unit} — <i>{p.flag}</i> "
                f"(Reference: {p.reference_range})", body_style
            ))
        story.append(Spacer(1, 8))

    # Contextual Notes
    if context_notes:
        story.append(Paragraph("Personalized Interpretation", heading_style))
        for n in context_notes:
            story.append(Paragraph(
                f"<b>{n['parameter']}</b>: {n['original_flag']} → <b>{n['adjusted_flag']}</b><br/>"
                f"{n['explanation']}", body_style
            ))
            story.append(Spacer(1, 6))

    # Pattern & Risk Findings
    if pattern_findings:
        story.append(Paragraph("Pattern & Risk Analysis", heading_style))
        for f in pattern_findings:
            story.append(Paragraph(
                f"<b>{f['pattern']}</b>: {f['value']} — <i>{f['risk_level']} Risk</i><br/>"
                f"{f['explanation']}", body_style
            ))
            story.append(Spacer(1, 6))

    # Summary
    story.append(Paragraph("Summary", heading_style))
    story.append(Paragraph(summary, body_style))
    story.append(Spacer(1, 8))

    # Recommendations
    story.append(Paragraph("Personalized Recommendations", heading_style))
    for rec in recommendations:
        story.append(Paragraph(f"• {rec}", body_style))
    story.append(Spacer(1, 16))

    # Disclaimer
    disclaimer_style = ParagraphStyle(
        "Disclaimer", parent=styles["Normal"], fontSize=8,
        textColor=colors.grey, spaceBefore=12
    )
    story.append(Paragraph(
        "This report was generated by an AI system and is intended for informational "
        "purposes only. It is not a substitute for professional medical advice, diagnosis, "
        "or treatment. Always consult a qualified healthcare provider regarding any medical "
        "concerns or before making changes to your diet, exercise, or treatment plan.",
        disclaimer_style
    ))

    doc.build(story)
    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes